# Generated by Django 4.1.3 on 2022-12-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_product_on_sale_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inventory',
        ),
        migrations.AddField(
            model_name='product',
            name='promotional_price',
            field=models.FloatField(default=0, verbose_name='Promotional Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, default=0, verbose_name='Stock'),
        ),
    ]
